spring.application.name=x-product
server.port=8081

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/xproduct_db?useSSL=false&serverTimezone=Asia/Colombo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=xProductSecretKey2024SuperSecureKeyForJWTTokenGenerationAndValidation
app.jwt.expiration=86400000

# Timezone
spring.jackson.time-zone=Asia/Colombo

# Logging
logging.level.com.xproduct=INFO
